# Generated by Django 6.0.8 on 2026-09-27 22:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlantis_site', '0069_metricssnapshot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeekReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_index', models.PositiveSmallIntegerField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='week_reminders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user_id', 'week_index'],
                'constraints': [models.UniqueConstraint(fields=('user', 'week_index'), name='one_reminder_per_user_week')],
            },
        ),
    ]
